resolver: lts-10.4

packages:
- '.'
- location:
    git: git@github.com:theNerd247/simple
    commit: dcba08858ffc85040bf8b85922fbc0ebb5f32be6
  subdirs:
    - simple
    - simple-aeson
    - simple-snap
    - simple-string
  extra-dep: true

allow-newer: true

extra-deps:
  - snap-1.0.0.2
  - heist-1.0.1.0
  - map-syntax-0.2.0.2
  - xmlhtml-0.2.5.1

nix:
  enable: false
  packages: 
    - zlib
    - libcxx
    - icu
    - gmp
    - gcc
    - ncurses
    - cabal-install
